/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Board Configuration
 */
#define CONFIG_CPU_BA2 1
#define CONFIG_GLOBAL_DATA_PTR 1
#define CONFIG_ROM_VER (2)
#define CONFIG_CRYSTAL_CLK (40000000)
#define CONFIG_AT_CMD_FUNC 1
#define CONFIG_UR_FLOW_CONTROL 1
#define CONFIG_UR_RTS (16)
#define CONFIG_UR_CTS (17)

/*
 * Basic Networkng
 */
#define CONFIG_FREERTOS 1
#define CONFIG_IPV4 1
#define MEMP_NUM_NETCONN (6)
#define CONFIG_LWIP 1
#define CONFIG_SOCKET_API 1
#define CONFIG_DHCPS 1
#define CONFIG_DHCPC 1
#define CONFIG_PING 1
#define CONFIG_DNS 1
//#define CONFIG_AXTLS 1

/*
 * Wireless LAN
 */
#define CONFIG_WLA 1
#define CONFIG_RFC 1
#define CONFIG_RFC_AT_BOOT 1
#define CONFIG_CH14 1
#define CONFIG_WLA_PATCH_V2 1
#define CONFIG_LARGE_DESCRIPTOR 1
#define CONFIG_WLA_KEEPALIVE 1
#define CONFIG_WLA_KEEPALIVE_TSF_ERR 1
#define CONFIG_RATEADAPTION2 1
#define CONFIG_AP 1
#define CONFIG_WPA 1
#define CONFIG_WEP 1
#define CONFIG_OMNICONFIG 1
#define CONFIG_REBOOT_ON_PANIC 1
#define CONFIG_WLA_LED 1
#define CONFIG_MINIFS	1
#define CONFIG_WEBSERVER 1
#define CONFIG_DNSSEVRER 1

